import sys
from PyQt6 import QtCore, QtGui, QtWidgets

# Form implementation generated from reading ui file 'sign-up.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

class Ui_SignupWindow(object):
    def setupUi(self, SignupWindow):
        SignupWindow.setObjectName("SignupWindow")
        SignupWindow.resize(1920, 1080)
        font = QtGui.QFont()
        font.setPointSize(14)
        SignupWindow.setFont(font)
        SignupWindow.setStyleSheet("background-color: #6fa8dc;\n"
"    ")
        self.titleLabel = QtWidgets.QLabel(parent=SignupWindow)
        self.titleLabel.setGeometry(QtCore.QRect(650, 60, 631, 151))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("font: 36pt \"Arial\"; color: white;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.rightPanel = QtWidgets.QFrame(parent=SignupWindow)
        self.rightPanel.setGeometry(QtCore.QRect(600, 250, 700, 400))
        self.rightPanel.setStyleSheet("background-color: #dddddd; border-top-right-radius: 15px; border-radius: 15px;")
        self.rightPanel.setObjectName("rightPanel")
        self.signupLabel = QtWidgets.QLabel(parent=self.rightPanel)
        self.signupLabel.setGeometry(QtCore.QRect(401, 20, 200, 40))
        self.signupLabel.setStyleSheet("font: 20pt \"Arial\";")
        self.signupLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.signupLabel.setObjectName("signupLabel")
        self.firstNameLineEdit = QtWidgets.QLineEdit(parent=self.rightPanel)
        self.firstNameLineEdit.setGeometry(QtCore.QRect(350, 80, 300, 40))
        self.firstNameLineEdit.setObjectName("firstNameLineEdit")
        self.lastNameLineEdit = QtWidgets.QLineEdit(parent=self.rightPanel)
        self.lastNameLineEdit.setGeometry(QtCore.QRect(350, 140, 300, 40))
        self.lastNameLineEdit.setObjectName("lastNameLineEdit")
        self.emailLineEdit = QtWidgets.QLineEdit(parent=self.rightPanel)
        self.emailLineEdit.setGeometry(QtCore.QRect(350, 200, 300, 40))
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.passwordLineEdit = QtWidgets.QLineEdit(parent=self.rightPanel)
        self.passwordLineEdit.setGeometry(QtCore.QRect(350, 260, 300, 40))
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.signupButton = QtWidgets.QPushButton(parent=self.rightPanel)
        self.signupButton.setGeometry(QtCore.QRect(450, 320, 100, 40))
        self.signupButton.setStyleSheet("background-color: #004aad; color: white; border-radius: 10px; font: 12pt \"Arial\";")
        self.signupButton.setObjectName("signupButton")
        self.leftPanel = QtWidgets.QFrame(parent=self.rightPanel)
        self.leftPanel.setGeometry(QtCore.QRect(3, 3, 294, 394))
        self.leftPanel.setStyleSheet("background-color: #004aad; border-top-left-radius: 15px; border-radius: 15px;")
        self.leftPanel.setObjectName("leftPanel")
        self.frame = QtWidgets.QFrame(parent=SignupWindow)
        self.frame.setGeometry(QtCore.QRect(596, 246, 708, 408))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("background-color: #000000;\n"
"border-radius:19px\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.titleLabel.raise_()
        self.rightPanel.raise_()

        self.retranslateUi(SignupWindow)
        QtCore.QMetaObject.connectSlotsByName(SignupWindow)

    def retranslateUi(self, SignupWindow):
        _translate = QtCore.QCoreApplication.translate
        SignupWindow.setWindowTitle(_translate("SignupWindow", "Signup"))
        self.titleLabel.setText(_translate("SignupWindow", "CC15 Banking System"))
        self.signupLabel.setText(_translate("SignupWindow", "Signup"))
        self.firstNameLineEdit.setPlaceholderText(_translate("SignupWindow", "First name"))
        self.lastNameLineEdit.setPlaceholderText(_translate("SignupWindow", "Last name"))
        self.emailLineEdit.setPlaceholderText(_translate("SignupWindow", "Email"))
        self.passwordLineEdit.setPlaceholderText(_translate("SignupWindow", "Password"))
        self.signupButton.setText(_translate("SignupWindow", "Signup"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_SignupWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())

