# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TransactionsHistory.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TransactionsHistory(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(979, 719)
        MainWindow.setMinimumSize(QtCore.QSize(960, 540))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")


        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #004aad;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(500, 400))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("""
            QTableWidget {
                background-color: rgb(255, 255, 255);
                font: 75 16pt 'MS Shell Dlg 2';
                border: 2px solid #004aad;
                border-radius: 12px;
                padding: 9px;
            }
            QHeaderView::section {
                background-color: #004aad;
                color: white;
                font: bold 16pt 'MS Shell Dlg 2';
                border: 1px solid #004aad; 
                border-radius: 12px;
                margin: 2px; 
                padding: 5px;
            }
        """)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)

        font = QtGui.QFont()
        font.setBold(True)
        font.setPointSize(16)

        header_labels = ["Transfers", "Deposits", "Withdrawal"]
        for col_index, header in enumerate(header_labels):
            item = QtWidgets.QTableWidgetItem(header)
            item.setFont(font)
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            item.setFlags(QtCore.Qt.ItemIsEnabled)  
            self.tableWidget.setHorizontalHeaderItem(col_index, item)

        self.tableWidget.horizontalHeader().setDefaultAlignment(QtCore.Qt.AlignCenter)
        header = self.tableWidget.horizontalHeader()
        header.setSectionResizeMode(QtWidgets.QHeaderView.Stretch)

        self.verticalLayout.addWidget(self.tableWidget, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)

        
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setStyleSheet("""
    QPushButton {
        background-color: #004aad;
        color: white;
        border-radius: 15px; 
        padding: 10px 24px;
        font-weight: bold;
        font-size: 14px;
        border: 2px solid #004aad; 
    
    }
    QPushButton:pressed {
        background-color: #015a8d;
    }
""")
        self.pushButton.setFlat(False)  
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

       

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Transactions History"))
        self.label.setText(_translate("MainWindow", "Transactions History"))
        self.pushButton.setText(_translate("MainWindow", "Back"))

        
      
        self.tableWidget.resizeRowsToContents()
        self.tableWidget.setWordWrap(True)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_TransactionsHistory()
    ui.setupUi(MainWindow)
    MainWindow.showMaximized()
    sys.exit(app.exec_())