# Form implementation generated from reading ui file 'navbar.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 498)
        Form.setStyleSheet("QPushButton:checked {\n"
"border-left: 4px solid #004aad;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar_container = QtWidgets.QGroupBox(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebar_container.sizePolicy().hasHeightForWidth())
        self.sidebar_container.setSizePolicy(sizePolicy)
        self.sidebar_container.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sidebar_container.setStyleSheet("background: #eaf3ff;\n"
"border: 0;")
        self.sidebar_container.setTitle("")
        self.sidebar_container.setObjectName("sidebar_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sidebar_container)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bank_logo = QtWidgets.QLabel(parent=self.sidebar_container)
        self.bank_logo.setStyleSheet("border: 0;\n"
"")
        self.bank_logo.setText("")
        self.bank_logo.setPixmap(QtGui.QPixmap("../icons/account_balance_92dp_004AAD_FILL0_wght400_GRAD0_opsz48.svg"))
        self.bank_logo.setObjectName("bank_logo")
        self.verticalLayout_2.addWidget(self.bank_logo, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.btn_vertical_layout = QtWidgets.QVBoxLayout()
        self.btn_vertical_layout.setSpacing(18)
        self.btn_vertical_layout.setObjectName("btn_vertical_layout")
        self.btn_dashboard = QtWidgets.QPushButton(parent=self.sidebar_container)
        self.btn_dashboard.setStyleSheet("QPushButton {\n"
"background: #eaf3ff;\n"
"color: #004aad;\n"
"text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border-left: 4px solid #004aad;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/home_24dp_004AAD_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_dashboard.setIcon(icon)
        self.btn_dashboard.setIconSize(QtCore.QSize(32, 32))
        self.btn_dashboard.setObjectName("btn_dashboard")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.btn_dashboard)
        self.btn_vertical_layout.addWidget(self.btn_dashboard)
        self.btn_account = QtWidgets.QPushButton(parent=self.sidebar_container)
        self.btn_account.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_account.setStyleSheet("QPushButton {\n"
"background: #eaf3ff;\n"
"color: #004aad;\n"
"text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border-left: 4px solid #004aad;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/credit_card_24dp_004AAD_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_account.setIcon(icon1)
        self.btn_account.setIconSize(QtCore.QSize(32, 32))
        self.btn_account.setObjectName("btn_account")
        self.buttonGroup.addButton(self.btn_account)
        self.btn_vertical_layout.addWidget(self.btn_account)
        self.btn_withdraw = QtWidgets.QPushButton(parent=self.sidebar_container)
        self.btn_withdraw.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_withdraw.setStyleSheet("QPushButton {\n"
"background: #eaf3ff;\n"
"color: #004aad;\n"
"text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border-left: 4px solid #004aad;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/money_24dp_004AAD_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_withdraw.setIcon(icon2)
        self.btn_withdraw.setIconSize(QtCore.QSize(32, 32))
        self.btn_withdraw.setObjectName("btn_withdraw")
        self.buttonGroup.addButton(self.btn_withdraw)
        self.btn_vertical_layout.addWidget(self.btn_withdraw)
        self.btn_deposit = QtWidgets.QPushButton(parent=self.sidebar_container)
        self.btn_deposit.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_deposit.setStyleSheet("QPushButton {\n"
"background: #eaf3ff;\n"
"color: #004aad;\n"
"text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border-left: 4px solid #004aad;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../icons/payments_24dp_004AAD_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_deposit.setIcon(icon3)
        self.btn_deposit.setIconSize(QtCore.QSize(32, 32))
        self.btn_deposit.setObjectName("btn_deposit")
        self.buttonGroup.addButton(self.btn_deposit)
        self.btn_vertical_layout.addWidget(self.btn_deposit)
        self.btn_transfer = QtWidgets.QPushButton(parent=self.sidebar_container)
        self.btn_transfer.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_transfer.setStyleSheet("QPushButton {\n"
"background: #eaf3ff;\n"
"color: #004aad;\n"
"text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border-left: 4px solid #004aad;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../icons/send_24dp_004AAD_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_transfer.setIcon(icon4)
        self.btn_transfer.setIconSize(QtCore.QSize(32, 32))
        self.btn_transfer.setObjectName("btn_transfer")
        self.buttonGroup.addButton(self.btn_transfer)
        self.btn_vertical_layout.addWidget(self.btn_transfer)
        self.btn_history = QtWidgets.QPushButton(parent=self.sidebar_container)
        self.btn_history.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_history.setStyleSheet("QPushButton {\n"
"background: #eaf3ff;\n"
"color: #004aad;\n"
"text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border-left: 4px solid #004aad;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../icons/history_24dp_004AAD_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_history.setIcon(icon5)
        self.btn_history.setIconSize(QtCore.QSize(32, 32))
        self.btn_history.setObjectName("btn_history")
        self.buttonGroup.addButton(self.btn_history)
        self.btn_vertical_layout.addWidget(self.btn_history)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.btn_vertical_layout.addItem(spacerItem1)
        self.btn_logout = QtWidgets.QPushButton(parent=self.sidebar_container)
        self.btn_logout.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_logout.setStyleSheet("QPushButton {\n"
"background: #eaf3ff;\n"
"color: #004aad;\n"
"text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border-left: 4px solid #004aad;\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../icons/logout_24dp_004AAD_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_logout.setIcon(icon6)
        self.btn_logout.setIconSize(QtCore.QSize(32, 32))
        self.btn_logout.setObjectName("btn_logout")
        self.buttonGroup.addButton(self.btn_logout)
        self.btn_vertical_layout.addWidget(self.btn_logout)
        self.verticalLayout_2.addLayout(self.btn_vertical_layout)
        self.verticalLayout_2.setStretch(2, 1)
        self.horizontalLayout.addWidget(self.sidebar_container)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_dashboard.setText(_translate("Form", "Dashboard"))
        self.btn_account.setText(_translate("Form", "Account and Card"))
        self.btn_withdraw.setText(_translate("Form", "Withdraw Money"))
        self.btn_deposit.setText(_translate("Form", "Deposit Money"))
        self.btn_transfer.setText(_translate("Form", "Transfer Money"))
        self.btn_history.setText(_translate("Form", "Transaction History"))
        self.btn_logout.setText(_translate("Form", "Log Out"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
