# Form implementation generated from reading ui file 'signup_resized.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 540)
        MainWindow.setStyleSheet("background: #ffffff")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #004aad;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setStyleSheet("background: #daf0f7;\n"
"border: 2px solid #004aad;\n"
"border-radius: 4px;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.groupBox_2)
        self.groupBox_3.setStyleSheet("background: #004aad;\n"
"border-radius: 8px;")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(parent=self.groupBox_2)
        self.groupBox.setStyleSheet("border: 0;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.first_name = QtWidgets.QLineEdit(parent=self.groupBox)
        self.first_name.setStyleSheet("border: 1px solid #004aad;\n"
"background: #daf0f7;")
        self.first_name.setObjectName("first_name")
        self.verticalLayout.addWidget(self.first_name)
        self.last_name = QtWidgets.QLineEdit(parent=self.groupBox)
        self.last_name.setStyleSheet("border: 1px solid #004aad;\n"
"background: #daf0f7;")
        self.last_name.setObjectName("last_name")
        self.verticalLayout.addWidget(self.last_name)
        self.user_name = QtWidgets.QLineEdit(parent=self.groupBox)
        self.user_name.setStyleSheet("border: 1px solid #004aad;\n"
"background: #daf0f7;")
        self.user_name.setObjectName("user_name")
        self.verticalLayout.addWidget(self.user_name)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.password_field = QtWidgets.QLineEdit(parent=self.groupBox)
        self.password_field.setStyleSheet("border: 1px solid #004aad;\n"
"background: #daf0f7;")
        self.password_field.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_field.setObjectName("password_field")
        self.verticalLayout.addWidget(self.password_field)
        self.confirm_password_field = QtWidgets.QLineEdit(parent=self.groupBox)
        self.confirm_password_field.setStyleSheet("border: 1px solid #004aad;\n"
"background: #daf0f7;")
        self.confirm_password_field.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.confirm_password_field.setObjectName("confirm_password_field")
        self.verticalLayout.addWidget(self.confirm_password_field)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.btn_register = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_register.setMinimumSize(QtCore.QSize(90, 30))
        self.btn_register.setStyleSheet("QPushButton{\n"
"background: #004aad;\n"
"color: #ffffff;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background: #69a9ff;\n"
"}")
        self.btn_register.setObjectName("btn_register")
        self.verticalLayout.addWidget(self.btn_register, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(6, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 5)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "CC15 Banking System"))
        self.label.setText(_translate("MainWindow", "Sign up"))
        self.first_name.setPlaceholderText(_translate("MainWindow", "First Name"))
        self.last_name.setPlaceholderText(_translate("MainWindow", "Last Name"))
        self.user_name.setPlaceholderText(_translate("MainWindow", "Username"))
        self.password_field.setPlaceholderText(_translate("MainWindow", "Password"))
        self.confirm_password_field.setPlaceholderText(_translate("MainWindow", "Confirm Password"))
        self.btn_register.setText(_translate("MainWindow", "Sign up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
