# Form implementation generated from reading ui file 'withdraw_panel.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(453, 322)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(parent=Form)
        self.groupBox.setStyleSheet("border: 0;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #004aad;")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_2.setStyleSheet("background: #daf0f7;\n"
"border-radius: 4px;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.balance_tag = QtWidgets.QLabel(parent=self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.balance_tag.setFont(font)
        self.balance_tag.setObjectName("balance_tag")
        self.verticalLayout_2.addWidget(self.balance_tag)
        self.balance_label = QtWidgets.QLabel(parent=self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.balance_label.setFont(font)
        self.balance_label.setObjectName("balance_label")
        self.verticalLayout_2.addWidget(self.balance_label)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.amount_box = QtWidgets.QLineEdit(parent=self.groupBox)
        self.amount_box.setMinimumSize(QtCore.QSize(0, 30))
        self.amount_box.setStyleSheet("border: 1px solid gray;")
        self.amount_box.setText("")
        self.amount_box.setObjectName("amount_box")
        self.verticalLayout.addWidget(self.amount_box)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.btn_confirm = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_confirm.setMinimumSize(QtCore.QSize(90, 30))
        self.btn_confirm.setStyleSheet("background: #004aad;\n"
"color: #ffffff;\n"
"border-radius: 4px;")
        self.btn_confirm.setObjectName("btn_confirm")
        self.verticalLayout_3.addWidget(self.btn_confirm, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.verticalLayout_5.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "WITHDRAW MONEY"))
        self.balance_tag.setText(_translate("Form", "CURRENT BALANCE"))
        self.balance_label.setText(_translate("Form", "12700.84"))
        self.label_3.setText(_translate("Form", "Enter amount"))
        self.btn_confirm.setText(_translate("Form", "Confirm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
